version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: flask_project3_image
    container_name: flask-project3a
    ports:
      - "5005:5000"
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: "1"
